-name: Set timezone to Asia/Jakarta
  timezone:
    name: Asia/Jakarta

- name: Update sshd config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - Restart sshd

- name: Create /root/.ssh dir
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- stat: path=/root/.ssh/authorized_keys
  register: status

- name: Remove file attributes for authorized_key
  shell: /usr/bin/chattr -ia /root/.ssh/authorized_keys
  ignore_errors: True
  when: status.stat.exists is defined

- name: Set authorized_keys for root user
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    mode: 0600

- name: Disable SELinux
  selinux:
    state: disabled
