- name: Set timezone to Asia/Jakarta
  timezone:
    name: Asia/Jakarta

- name: Update sshd config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd

- name: Create /root/.ssh dir
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: Set authorized_keys for root user
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    mode: 0600

- name: Disable SELinux
  selinux:
    state: disabled
