- name: Install MysQL
  yum:
    name: '{{ item }}'
  with_items:
  - mariadb-server
  - mariadb
  - MySQL-python

- name: Start the MySQL service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Wait for MySQL daemon to be up seem make sure that mariadb is started
  wait_for:
    path: "/var/lib/mysql/mysql.sock"
    state: present

- debug:
    msg: "{{ mysql_root_password }}"

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
